### ISSUE TITLE
Deployment Error

### ISSUE THREAD

**Issue by BlockI0tChain** [heroyooki/EVerythingcharge#2]
Hello heroyooki,

Thanks! Awesome work on this OCPP stack! 

I've tried to deploy it locally as per your "Raise app on the single serve" instructions and encountered some error. 
Have a look at the run here:  [**Pastebin**](https://pastebin.com/xY65c3GB) and please tell me if you can, what's the issue.

Thank you! Cheers BIC

**Comment by heroyooki** [comment]
I need namely those variables
DB_NAME=
DB_PASSWORD=
DB_PORT=5432
DB_USER=
DB_HOST=

**Comment by BlockI0tChain** [comment]
I've used such config for the db block:

DB_NAME=testdb
DB_PASSWORD=testy
DB_PORT=5432
DB_USER=test
DB_HOST=everythingcharge-db

**Comment by BlockI0tChain** [comment]
Nvm, with your latest update i managed to start the stack, 
    this error `No module named 'aiokafka' `  is still there however. 
    Also logging into the UI with `user admin` doesn't do anything yet.

**Comment by heroyooki** [comment]
`No module named 'aiokafka'` is not an error.
The UI is empty yet because the app is in progress.

**Comment by heroyooki** [comment]
Closed
